### ISSUE TITLE
How to deal with old job postings (was: Expiry date for submissions)

### ISSUE THREAD

**Issue by moba** [fossjobs/fossjobs#14]
It would be nice to allow submissions to specify an "end date", and then either hide expired job listings or display them as greyed out. We could also "grey out" listings that are older than 2 months or so by default.

I actually like how the site lists old job postings, as an archive of FOSS organizations and to demonstrate that there are in fact jobs in FOSS.

**Comment by justinclift** [comment]
> I actually like how the site lists old job postings ...

Might be better to have them moved to an "Archive" section though.

Having old jobs in the main section seems like a bad idea.  The just pad out the number of results in listings, and turn out to be useless for anyone using the site for actual job finding. :wink:

After clicking through a few of the old/expired postings, people aren't going to keep on looking just in the hope the next one is actually recent.

**Comment by KaiRo-at** [comment]
Of course, it would be even more helpful if those that post the job would label them as "not up for hiring any more" in some form - the outward facing message of an archive list of "has been hired, not open any more" is even better than "expired" ;-)

**Comment by justinclift** [comment]
Yeah, probably not practical to expect consistent follow up from the people posting listings though. :wink:

**Comment by waldyrious** [comment]
> Having old jobs in the main section seems like a bad idea. They just pad out the number of results in listings

Why does that matter? I think a cumulative total is actually more useful (from a historical perspective, as @moba mentioned in the opening comment) than a total of recent openings only, since job seekers wouldn't care about the number of openings anyway, but instead with whether each opening is a good match. So I don't see that as a downside.

> ...and turn out to be useless for anyone using the site for actual job finding.

At least they don't actively harm them (if appropriately marked as old). On the other hand there's the upside of having a highly visible archive of past postings, that could encourage people to post new openings.

The alternative of having old entries tucked away at a separate archive page would make the site appear empty probably less likely to receive contributions because of that. Not to mention it would probably require a more complex implementation :)

> We could also "grey out" listings that are older than 2 months or so by default.

I agree with greying out, but I'd suggest using a 3 months window instead.

**Comment by justinclift** [comment]
> Why does that matter?

So the display is actually useful? :smile:

Just from the point of view of the statement in my original comment "After clicking through a few of the old/expired postings, people aren't going to keep on looking just in the hope the next one is actually recent."

There's nothing wrong with having legacy data.  But make sure it's not interfering with people trying to use the site for what seems to be its primary purpose.

On the other hand, it was just a throw-away thought anyway, so YMMV. :smile:

**Comment by waldyrious** [comment]
> people aren't going to keep on looking just in the hope the next one is actually recent.

Not sure I get what you're saying. Even if the counts reflected only recent posts, one would have to keep visiting the site anyway, memorizing the old count(s) and comparing them with the new ones, in order to infer whether there are new posts or not. It is a rather indirect, workaround-y (and I'd even say inconvenient) way to check for new postings.

Considering that (1) there are RSS feeds available, and the Twitter account one can follow; and that (2) the counts would both increase with new posts but also decrease as old postings are removed, I don't think it makes sense to hinge on the counts for checking for new posts. But please correct me if I'm misunderstanding.

**Comment by justinclift** [comment]
Well, when I first came across the site it was super frustrating.  I'd click on a role... oh, it's ancient.

Click the next one... same.  And the next, etc.

Things may have changed.  If so, ignore this. :smile:

**Comment by moba** [comment]
I think it's fine to discuss this. I think we should separate a bit the "archive" function and how it is important not to fully remove old job posts, and the point that was raised here (and elsewhere) about the "number of total jobs" and the "jobs per category" on the front page.

The most important aspect for me is that one can see who has offered paid positions in the past, which means there is quite a chance that they have some similar demand now or in the near future (but not announced it yet). Merely learning which projects out there do offer jobs from time to time can help encourage people to start contributing and become members of the project community, which is my motivation for running this site: Getting more people into FOSS in the first place. You're unlikely to get a job from the job postings alone, and much more likely to be considered if you're already around as a community member, after all. Which is why I would say it should not be "frustrating" to see that a cool project has offered the perfect position for me half a year ago, but actually "encouraging" to get in touch with the project and learn more about it, so when the time comes you're already in the right place.

**That said, I agree that it would be nicer for the front page display to count only active jobs (2-3 months old) in both the summary and the category display, and to highlight active jobs in the respective categories.** <- Feature Request :)

**Comment by moba** [comment]
I have now hackishly changed a few queries to only count submissions within the past 3 months: You can see this for example on the front page sidebar, the per country counts and the "total jobs" count.

**Comment by justinclift** [comment]
@moba Thanks, that front page side bar does look useful now.  Just tried it out, and seems to work ok. :smile:

**Comment by moba** [comment]
Recent job posts now get extra treatment and an additional "recent" css class in the listings ([commit 36ed13f ](https://github.com/fossjobs/fossjobs/commit/36ed13f636c33032735ee72327fb7890568957e5)). For now this means they get printed in bold, but maybe someone wants to experiment with a nicer way of highlighting (slight change to the background color of the row perhaps?).

**Comment by justinclift** [comment]
Just went looking... but didn't notice a difference.  Might be just the way my browser (FF on CentOS 7) is displaying things, not sure. :smile:

**Comment by pabs3** [comment]
I had a thought: how about a reconfirmation email every X months for
all "open jobs". So the submitter has to click "still open" or
"filled", otherwise the job gets set to "expired" and the status is
displayed on the website.

This would require codebase modifications though so probably should
wait until using switching to non-abandoned project.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by waldyrious** [comment]
> For now this means they get printed in bold, but maybe someone wants to experiment with a nicer way of highlighting (slight change to the background color of the row perhaps?).

I think it might look better if *non-recent* posts are faded out, rather than the recent ones emphasized. With longer lists (as is the case with the  [programmers](https://www.fossjobs.net/jobs/programmers/) category for example) the proportion or recent entries is high enough to cover more than a screenful, so that ends up making all visible entries bold.

**Comment by moba** [comment]
The site now features mostly "recent" jobs. The archive is kept, and job postings older than 30 days have a big warning about their age on the top. I guess I can close this topic for now. Feel free to reopen if you want to continue the discussion.
