### ISSUE TITLE
Data quality issue: Zurich, Swaziland

### ISSUE THREAD

**Issue by jayaddison** [fossjobs/fossjobs#44]
Possibly due to an attempt to approximate-match (or screen-ocr) the country name?

![image](https://user-images.githubusercontent.com/55152140/123324645-f2951300-d52e-11eb-8589-2f061f3f80af.png)

**Comment by moba** [comment]
On the submission form, people enter city names themselves, and can select a country via dropdown. We are a volunteer project, and while we do check submissions, "data quality" is really the responsibility of the submitter. It seems to work fine in most cases. We don't do any "matching" or OCR as a platform. Looks like a submitter used the keyboard and entered "Sw", and didn't expect Swaziland to come before Switzerland in the list of countries.

We can go fix that particular submission. I probably wouldn't even have accepted them in the first place because it does not look like actual open source development, but sometimes things like that slip through. We are short-handed in terms of reviewers, and welcome assistance.

**Comment by moba** [comment]
Fixed the two submissions now.

**Comment by jayaddison** [comment]
Thanks @moba!
